### ISSUE TITLE
Agile or Waterfall?

### ISSUE THREAD

**Issue by eggsactly** [MiSTERSPOONS/Kapture#68]
Was this project developed using agile or waterfall? 
I'm doing a research paper for my systems engineering class about development methodologies and I want to see if they have an impact on commit patterns.

**Comment by MiSTERSPOONS** [comment]
Hi @eggsactly We used an Agile methodology!

**Comment by eggsactly** [comment]
Jonathan. Thank you for getting back to me. Your reply helps my project. I appreciate it.

**Comment by MiSTERSPOONS** [comment]
@eggsactly No problem. Glad I can be of assistance!

**Comment by eggsactly** [comment]
@MiSTERSPOONS would you mind filling out a survey about your experience on your capstone?
https://www.mysurveygizmo.com/s3/4945760/Product-Development-Methods-on-Engineering-Disciplines-Survey
My research team decided to issue a survey for our research project.
